"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false
continuation_prompt = "▶▶"

# Left prompt
format = """
$directory\
$git_branch\
$git_state\
${custom.git_status_dirty}\
$git_status\
$aws\
$character"""

# Right prompt
right_format = """
$cmd_duration\
$status\
$python \
$kubernetes \
"""

# Left config
[directory]
truncation_symbol = "…/"

# [python]
# format = 'via [${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)'

[aws]
format = '[$symbol($profile)(\($region\))(\[$duration\])]($style)'
force_display = true

[kubernetes]
format = '[$symbol$context(\($namespace\))]($style)'
style = "cyan"
disabled = false

[git_branch]
format = "[$branch]($style)"
style = "bright-black"

[git_status]
format = "[($ahead_behind$stashed)]($style)"
style = "cyan"
stashed = "≡"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain)"'
symbol = "*"
style = "purple"
format="[$symbol]($style) "
shell = ["bash", "--norc", "--noprofile"]

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[package]
disabled = true

# Right config
[status]
disabled = false
format = "[$symbol $status]($style) "
