# Inserts a blank line between shell prompts
add_newline = false
continuation_prompt = "▶▶"

# Left prompt
format = """
$directory\
$docker_context\
$container\
$aws\
$env_var\
$custom\
$sudo\
$jobs\
$shell\
$character"""

# Right prompt
right_format = """
$cmd_duration\
$status\
$git_state\
$git_status\
$git_branch\
$kubernetes\
"""


# Left config
[directory]
truncation_symbol = "…/"
truncate_to_repo = true
read_only = " "

# Right config

[status]
disabled = false
format = "[$symbol $status]($style) "

[aws]
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
force_display = true
symbol = "  "

[kubernetes]
format = '[$symbol$context(\($namespace\))]($style) '
style = "cyan"
disabled = false
symbol = "⚙️ "

[git_branch]
format = "[$symbol$branch]($style) "
style = "105"
symbol = "שׂ "

[git_status]
format = '([(\[$all_status\]) $ahead_behind]($style) )'
style = 'bold blue'
conflicted = '[=](bold red)'
ahead = '[$count⇡](bold 198)'
behind = '[$count⇣](bold 198)'
diverged = '[${ahead_count}⇡${behind_count}⇣](bold 198)'
up_to_date = '[✓](bold 34)'
untracked = '[$count?](bold 228)'
stashed = '[$count≡](bold cyan)'
modified = '[$count!](bold purple)'
staged = '[$count+](bold 34)'
renamed = '[$count»](bold white)'
deleted = '[$count✘](bold red)'

[docker_context]
symbol = " "

[package]
disabled = true
