[tools]
aws-vault = '6.6.0'
chezmoi = '2.46.0'
elixir = '1.15.7-otp-26'
erlang = '26.2.1'
kubectl = '1.29.0'
kubectx = '0.9.5'
k3d = '5.6.0'
k9s = '0.29.1'
nodejs = 'lts'
python = ['3.10']
terraform = '1.6.6'
